#' Build network
#'
#' @description \code{build_network()} establishes network structures between genes
#' in different predicted time points.
#' @param mucl a dataframe containing strength of pairwise-gene linear relationship in
#' different predicted time points. This dataframe could be generated by function
#'  \code{\link{dynamic_linear_relationship}}.
#' @param gene_name a vector of character containing gene names. It is recommended using
#' function \code{\link{dynamic_linear_relationship}} to generate \code{mucl} so that the order of
#' gene names of this parameter  is just the order in your \code{data}. See
#' \code{\link{dynamic_linear_relationship}} for details.
#' @param thres a threshold determine whether the edge exist in the network. When the
#' correlation between two genes is smaller than the threshold, the edge between these
#' genes will not exist.
#'
#' @return a list containing objects of class 'network'. Each element in
#' the list represents networks in different predicted time points.
#' @export
#'

build_network = function(mucl,gene_name,thres=0.4){
  network = list()
  l = length(mucl[1,])
  for (ii in 1:l){

    temp = mucl[,ii]
    class(temp) <- 'dist'
    attr(temp,'Size') <- length(gene_name)
    temp_corr = as.matrix(temp)
    colnames(temp_corr) = gene_name
    rownames(temp_corr) = gene_name


    temp_corr[temp_corr < thres] <- 0
    nn = network(temp_corr, directed = FALSE)
    network[[ii]] = nn
  }
  names(network) = seq(1,l)
  return(network)
}



