#' Get individual gene expression across cells
#'
#' @description \code{gene_expression()} returns individual gene expression across
#' cell lineages trajectories.
#' @param trajectory_expression a list of length \eqn{N},where \eqn{N} is
#' the number of cells in one time point(the number of cells need to be equal
#' among different time points). The \eqn{i}-th element in the list is a matrix with
#' \eqn{d} rows and \eqn{t} columns, giving the gene expression of \eqn{d} genes in \eqn{t} time
#' points of the \eqn{i}-th cell lineage trajectory. This list
#' could be generated by function \code{\link{trajectory_expression}}.
#'
#' @return a list of length \eqn{d}, where \eqn{d} is the number of genes. The elements
#' in the list representing the individual gene expression in \eqn{N} cell
#' lineages trajectories, each trajectory has \eqn{t} time points.
#' @export
#'
gene_expression <- function(trajectory_expression){
  gene_name = rownames(trajectory_expression[[1]])
  gene_expression = list()
  pb <- progress_bar$new(
    format = 'Processing [:bar] :percent eta: :eta',
    total = length(gene_name), clear = FALSE, width = 80)
  for (gene in gene_name){
    pb$tick()
    out_gene <- lapply(trajectory_expression, function(x) x[rownames(x) %in% gene, ])
    out_gene <- t(as.data.frame(out_gene))
    rownames(out_gene) <- NULL
    gene_expression[[gene]] <- out_gene
  }
  return(gene_expression)
}


