#' Gene community detection
#'
#' @description \code{gene_community_detection()} detects genes' community belongings
#' at each predicted time point.
#' @param network a list of length \code{npred}, where \code{npred} is the number of
#' predicted time points. Each element in the list is an object of class 'network'.
#' This list could be generated by function \code{\link{build_network}}.
#'
#' @return a list of length \code{npred}. Each element in the list is a dataframe containing
#' genes' community belongings.
#' @export
#'
gene_community_detection = function(network){
  group_louvain_label = list()
  l = length(network)
  for (ii in 1:l){
    net = network[[ii]]
    g2 <- asIgraph(net)
    lc <- cluster_louvain(g2)
    m = as.numeric(membership(lc))
    data = data.frame(gene = gene_name, group = m)
    group_louvain_label[[ii]] = data
  }
  names(group_louvain_label) = seq(1,l)
  return(group_louvain_label)
}
