#' Plot Umap with linked trajectories
#' @description \code{plot_linked_traj()} plots linked trajectories on gene expression data, which
#' dimension is reduced to two dimensions by Umap.
#' @param cell_name_traj a dataframe with \eqn{N} rows and \eqn{t} columns, giving \eqn{N} unique
#' trajectories for individual cells, each trajectory has length \eqn{t}. This dataframe could be
#' generated by function \code{\link{cell_name_traj}}.
#' @param umap_expression a dataframe including four columns. The first column is the cell name
#' consistent with the name in \code{cell_name_traj}. The second and third columns are gene expressions which
#' dimension is reduced to two dimensions by Umap. The forth column is integers start from 0,
#' indicating which time points the cell belongs to. The name of four columns need to be
#' 'id','Umap1','Umap2','time',respectively.
#' @param t0 \code{plot_linked_traj} plots trajectories from time 0 to time \eqn{t_0}. Default setting is
#'  plotting the whole trajectories, which is from time 0 to time \eqn{t-1}.
#' @param ntraj an integer indicating number of trajectories to be plotted. Trajectories are randomly
#' selected from dataframe \code{cell_name_traj}.
#' @param random_seed random seed for sampling the trajectories from dataframe \code{cell_name_traj}.
#'
#' @return a plot containing linked trajectories on two dimensional Umap data.
#' @export
#'

plot_linked_traj = function(umap_expression,cell_name_traj,t0=NULL,ntraj=10,random_seed=2022){
  #umap_expression <- merge(umap,cell_time,by="id")
  if(is.null(t0)){
    t0 = length(cell_name_traj[1,])-1
  }
  subset <- umap_expression[umap_expression$time <= t0,]

  tra_num = ntraj
  set.seed(random_seed)
  sub_traj = sample_n(cell_name_traj, tra_num)
  nn = as_vector(sub_traj)
  cell_subset <- subset[nn,]

  subset_vector = stack(sub_traj)$values
  subset_umap <- subset[subset$id %in% subset_vector, ]

  traject = seq(1:tra_num)
  traject_umap <- paste("traject ", traject, sep="")
  umap_group = rep(traject_umap,t0+1)
  subset_umap$group = umap_group

  ##add line
  line_connect = list()
  for (ii in 1:(t0+1)) {
    line_connect[[ii]] = subset_umap[subset_umap$time == (ii-1) | subset_umap$time == ii, ]
  }

  gra = ggplot(subset_umap, aes(Umap1, Umap2))+
    geom_point(data = subset_umap, aes(x = Umap1, y = Umap2, color = factor(time)))+
    xlab("Umap1") + ylab("Umap2")

  for (ii in 1:(t0)) {
    gra = gra + geom_line(data = line_connect[[ii]], aes(x = Umap1, y = Umap2, group = group), size = 0.1)
  }

  gra[["labels"]][["colour"]] = "Experimental Time"
  gra1 = gra + theme_bw() + theme(legend.position="bottom")
  return(gra1)
}
