#' Smoothing gene expression patterns for individual cells
#'
#' @description \code{smooth_cell_expression()} returns smoothing gene expression patterns for
#' individual cells by smoothing spline models. SSANOVA is used in this package.
#' Both fitted values at \eqn{t} time points and predicted values at
#' \code{npred} points are returned. \code{smooth_cell_expression()} first smooths the
#' gene expressions pattern for each gene along time, and extract the
#' ”mean curve” of all individual gene expression patterns to obtain the general
#' gene expression pattern, which is the output of \code{smooth_cell_expression()}.
#'
#' @param trajectory_expression a list of length \eqn{N}. The \eqn{i}-th element in the list is a matrix with
#' \eqn{d} rows and \eqn{t} columns, giving the gene expression of \eqn{d} genes in \eqn{t} time
#' points of the \eqn{i}-th cell lineage trajectory. This list
#' could be generated by function \code{\link{trajectory_expression}}.
#' @param npred an integer representing number of predicting points equally spaced between
#' 1 and \eqn{t}.
#'
#' @return a list of length two. The first element of the return contains the
#' predicted values of \code{npred} points in each cell trajectory. The second element of the
#' return contains the fitted values of \eqn{t} time points in each cell trajectory.
#'
#' @export
#'

smooth_cell_expression <- function(trajectory_expression,npred=300){
  pred_list = list()
  plot_list = list()

  pb <- progress_bar$new(
    format = 'Processing [:bar] :percent eta: :eta',
    total = length(trajectory_expression), clear = FALSE, width = 80)
  t = dim(trajectory_expression[[1]])[2]
  for (nn in 1:length(trajectory_expression)){
    pb$tick()

    data = trajectory_expression[[nn]]
    geneset_mclu_tran = t(data)
    data <- as.data.frame(geneset_mclu_tran)
    data$id <- 1:nrow(data)
    plot_data <- melt(data,id.var="id")
    yy <- plot_data$value
    cc <- plot_data$id
    id <- as.factor(plot_data$variable)

    fit.random <- ssanova(yy~cc)
    x = data.frame(cc = seq(1, t, length = npred))
    x2 = data.frame(cc = seq(1:t))
    pred2 <- predict(fit.random, newdata = x, se.fit = T )
    pred_point <- predict(fit.random, newdata = x2, se.fit = T )
    pred_list[[nn]] = pred2$fit
    plot_list[[nn]] = pred_point$fit
  }
  return(list(pred_list = pred_list,fitted_list = plot_list))
}




